### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Pi1998** [lucy-sees/HTML-CSS---JavaScript-capstone-project#2]

**Comment by ismayito** [comment]
Thanks for adding the project presentation link to your Readme file.
However I am seeing a horizontal scrollbar could you please kindly fix that

**Comment by AbuTalha3** [comment]
** Your Project is Done very well but there are some changes required**

-The pictures are not responsive, I suggest that you may work on CSS to make them responsive and hide them on the small screen.
![Screenshot 2023-08-15 122303](https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/127955219/cabd75b4-73a6-42b1-a873-e92146e601cb)

**Comment by Pi1998** [comment]
# Optional

- It looks much better if you can add some hover effects with color changes to your menu for better orientation and design purposes.  
- The both menu button and menu bar disappear at the screen width between 770px and 990px.
- Other than that, everything looks fine.
-

**Comment by lucy-sees** [comment]
Thank you for the suggestions

**Comment by lucy-sees** [comment]
Thank you for the suggestions
